### ISSUE TITLE
UI for auto/manual is not clear.

### ISSUE THREAD

**Issue by luciph0r** [sleepingkirby/ButWhyMdl#2]
The dropdown menu shows Automatic prune, and clicking it changes it to manual prune. This is a case of using the menu label as a status indicator, and is confusing at first. Would be good if you don't change the label and simply show a checkbox to indicate that automatic or manual pruning is on or off. 
UI convention is to show a checkbox for a toggle setting in a menu, else the user would think that it is supposed to visibly do something.

**Comment by sleepingkirby** [comment]
Hi. I'm so sorry. I don't know how I missed this. Which version are you using? I've stopped updating or firefox and palemoon because no one I know uses either. I'll make this update for chrome and push it out to the chrome webstore in a little bit. If you use another version, tell me and I'll updated it there.

**Comment by luciph0r** [comment]
Thanks for the reply, I've been using the Pale Moon version. Currently
it's hit version 29 and dropped support for installing legacy FF
extensions that don't explicitly target it, so several new ones forked
from Firefox have been added to its addons site. Was recommending your
extension as an alternative for other similar older ones, so would be
great if you could fix the UI on this and publish the update on the Pale Moon addons site.

**Comment by sleepingkirby** [comment]
I've changed applied the changes to the popup menu. I'm not sure why, but everytime I've reset the password for the palemoon addon dev panel, after using it once or twice and take a bit of a haitus, I can never log in again. I don't know if there's a password aging thing or what. There's also no good way to automatically recover/reset the password. I'll have to get in touch with Tobin (the creator and admin of palemoon) on IRC to ask to have it reset. I don't have time at the moment to do that. If you want the install now, it's here:
https://github.com/sleepingkirby/butWhyMod/blob/xul/releases/butWhyMod_xul.xpi
I'll try to contact Tobin to reset my password tomorrow.

**Comment by luciph0r** [comment]
Thanks for the fix! Yeah, he once said that they expire accounts that don't have any addons created to prevent people from simply creating dummy accounts - but this password expiry is strange.

**Comment by sergeevabc** [comment]
Dear @luciph0r, have you abandoned the development?

**Comment by sleepingkirby** [comment]
@sergeevabc 
No, but I need to figure something out. butWhyMod is need of a major overhaul due to how modals have changed in their implementation. This on top of the Chrome version being vastly ahead of the other two version and manifest v3 being a thing, the documentation for how to program for palemoon being, well, deprecated firefox documentation, I have a lot of work ahead. But at the same time, I have a full time job so this falling to the way side especially since I have 2 other extensions I haven't published but are available in my repo.
A good example is that butWhyMod on the Chrome side offers auto skip for any and all videos, can prevent autoplay of videos, and offers refined control of videos (rewind and fast forward in 20 sec, 1 sec, and 1/30 of a sec intervals, or some combination of the three).

**Comment by sergeevabc** [comment]
There is an alternative called [Demodal](https://addons.mozilla.org/en-US/firefox/addon/demodal/) by @AliasIO. Have been testing it for a month: missed a couple of cookie notices, but at least didn't force me to create exceptions.

**Comment by luciph0r** [comment]
I've since been content with modal filter lists for uBlock Origin, better than having a separate extension for the same job.

**Comment by sleepingkirby** [comment]
@sergeevabc @luciph0r 
I'm glad you guys found alternatives. Especially uBlock. They do good stuff. I do these for fun and my own purposes so I can't be as on the ball as they are. I'm gonna close this issue.
